version: "3"
services:
  app:
    container_name: app
    image: frebby/app2
    restart: always
    environment:
      - MONGO_URL=mongodb://mongo:27017/app2
    build: .
    ports:
      - "8081:8080"
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
  seed:
    container_name: seed
    image: frebby/seed-data
    restart: "no"
    build: ./dbSeed
    environment:
      - MONGO_URL=mongodb://mongo:27017/app2
    command: npm run seed
    links:
      - mongo
    depends_on:
      - mongo

volumes:
    mongo-data:
        driver: local